#!/bin/sh

# Generated by apply.py

# Backgrounds
BG="{{ ui.bg0 }}"
BG_ALT="{{ ui.bg1 }}"
BG_LIGHT="{{ ui.bg2 }}"
BG_HIGHLIGHT="{{ ui.bg3 }}"

# Foregrounds
FG="{{ text.fg0 }}"
FG_DIM="{{ text.fg1 }}"
FG_FAINT="{{ text.fg2 }}"
FG_DISABLED="{{ text.fg3 }}"

# Accents
ACCENT="{{ accent.primary }}"
ACCENT_ALT="{{ accent.secondary }}"

# ANSI
BLACK="{{ ansi.black }}"
RED="{{ ansi.red }}"
GREEN="{{ ansi.green }}"
YELLOW="{{ ansi.yellow }}"
BLUE="{{ ansi.blue }}"
MAGENTA="{{ ansi.magenta }}"
CYAN="{{ ansi.cyan }}"
WHITE="{{ ansi.white }}"
