# Generated by apply.py

# Completion
c.colors.completion.fg = "{{ text.fg0 }}"
c.colors.completion.odd.bg = "{{ ui.bg0 }}"
c.colors.completion.even.bg = "{{ ui.bg1 }}"
c.colors.completion.category.bg = "{{ accent.primary }}"
c.colors.completion.category.fg = "{{ ui.bg0 }}"

# Statusbar
c.colors.statusbar.normal.bg = "{{ text.fg2 }}"
c.colors.statusbar.normal.fg = "{{ ui.bg0 }}"

c.colors.statusbar.command.bg = "{{ ui.bg0 }}"
c.colors.statusbar.command.fg = "{{ text.fg0 }}"

c.colors.statusbar.insert.bg = "{{ accent.primary }}"
c.colors.statusbar.insert.fg = "{{ ui.bg0 }}"

# Tabs
c.colors.tabs.bar.bg = "{{ text.fg2 }}"

c.colors.tabs.selected.even.bg = "{{ ui.bg0 }}"
c.colors.tabs.selected.even.fg = "{{ text.fg0 }}"

c.colors.tabs.selected.odd.bg = "{{ ui.bg0 }}"
c.colors.tabs.selected.odd.fg = "{{ text.fg0 }}"

c.colors.tabs.even.bg = "{{ ui.bg1 }}"
c.colors.tabs.even.fg = "{{ text.fg1 }}"

c.colors.tabs.odd.bg = "{{ ui.bg1 }}"
c.colors.tabs.odd.fg = "{{ text.fg1 }}"

# Downloads
c.colors.downloads.bar.bg = "{{ text.fg2 }}"

# Hints
c.colors.hints.bg = "{{ ansi.yellow }}"
c.colors.hints.fg = "{{ text.fg0 }}"

# Messages
c.colors.messages.info.bg = "{{ ui.bg1 }}"
c.colors.messages.info.fg = "{{ text.fg0 }}"
