#!/bin/sh

# Generated by apply.py

bspc config normal_border_color "{{ ui.bg1 }}"
bspc config active_border_color "{{ accent.secondary }}"
bspc config focused_border_color "{{ accent.primary }}"
bspc config presel_feedback_color "{{ ansi.yellow }}"
