#!/bin/sh

# Generated by apply.py

bspc config normal_border_color "#D6C5A5"
bspc config active_border_color "#A17A50"
bspc config focused_border_color "#8C6846"
bspc config presel_feedback_color "#B88B45"
