# Generated by apply.py

# Completion
c.colors.completion.fg = "#584850"
c.colors.completion.odd.bg = "#E0D0B0"
c.colors.completion.even.bg = "#D6C5A5"
c.colors.completion.category.bg = "#8C6846"
c.colors.completion.category.fg = "#E0D0B0"

# Statusbar
c.colors.statusbar.normal.bg = "#7C675A"
c.colors.statusbar.normal.fg = "#E0D0B0"

c.colors.statusbar.command.bg = "#E0D0B0"
c.colors.statusbar.command.fg = "#584850"

c.colors.statusbar.insert.bg = "#8C6846"
c.colors.statusbar.insert.fg = "#E0D0B0"

# Tabs
c.colors.tabs.bar.bg = "#7C675A"

c.colors.tabs.selected.even.bg = "#E0D0B0"
c.colors.tabs.selected.even.fg = "#584850"

c.colors.tabs.selected.odd.bg = "#E0D0B0"
c.colors.tabs.selected.odd.fg = "#584850"

c.colors.tabs.even.bg = "#D6C5A5"
c.colors.tabs.even.fg = "#6A564B"

c.colors.tabs.odd.bg = "#D6C5A5"
c.colors.tabs.odd.fg = "#6A564B"

# Downloads
c.colors.downloads.bar.bg = "#7C675A"

# Hints
c.colors.hints.bg = "#B88B45"
c.colors.hints.fg = "#584850"

# Messages
c.colors.messages.info.bg = "#D6C5A5"
c.colors.messages.info.fg = "#584850"
